add first profile open
epfl-SDP/android pull request #142
Opened 2022-03-20 18:38 UTC by barmettlerl

2022-03-23 14:53 UTC, KurohanaJuri reviewed
I think that you messed up the naming in the nav bar. It's a bit strange that the settings map to the profile route

2022-03-24 09:44 UTC, KurohanaJuri commented on mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/setting/SettingScreenTest.kt
> +  fun counts_areDisplayed() {
`count`is a bit ambitious, since we have 2 counts. I suggest renaming this : 
```suggestion
  fun pastGameCount_areDisplayed() {
```

2022-03-24 10:47 UTC, KurohanaJuri approved these changes

2022-03-24 14:02 UTC, alexandrepiveteau requested changes
I'm a bit concerned by the duplication between the `SettingScreen` (which btw should probably be named `SettingsScreen`) and the `ProfileScreen` composables. In my opinion, this would be the perfect opportunity to use a slot-based approach ([documentation](https://developer.android.com/jetpack/compose/layouts/basics#slot-based-layouts)).

Additionally, users should be retrieved using their `uid` (especially since they're now available in the `Profile` interface, which should make your life a lot simpler).

2022-03-24 14:56 UTC, barmettlerl commented
> Additionally, users should be retrieved using their `uid` (especially since they're now available in the `Profile` interface, which should make your life a lot simpler).
@alexandrepiveteau this is something I will do in the next sprint

2022-03-24 14:58 UTC, barmettlerl commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/social/PersonCard.kt
> +      modifier = modifier.clickable { openProfile(person) },
Wouldn't this conflict with the `play` button which is also in the Card ?

2022-03-24 15:30 UTC, barmettlerl commented
> I'm a bit concerned by the duplication between the `SettingScreen` (which btw should probably be named `SettingsScreen`) and the `ProfileScreen` composables. In my opinion, this would be the perfect opportunity to use a slot-based approach ([documentation](https://developer.android.com/jetpack/compose/layouts/basics#slot-based-layouts)).
Very elegant. Thank you. I will apply it directly

2022-03-24 16:39 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/social/PersonCard.kt
> +      modifier = modifier.clickable { openProfile(person) },
Button uses a `Surface` internally, which blocks pointer inputs ([source code](https://github.com/androidx/androidx/blob/androidx-main/compose/material/material/src/commonMain/kotlin/androidx/compose/material/Surface.kt#L131)), so the button clicks should not conflict with a `clickable { }` which will be applied behind it to the whole `ListItem`.

2022-03-24 22:54 UTC, Fouad-sys approved these changes

2022-03-24 22:54 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/application/social/SocialFacade.kt
> +  fun get(name: String): Flow<Profile> {
[Nitpick] By our documentation convention, you could use the past tense for the function description and add the variable name next to the "@param"

2022-03-24 22:54 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/application/social/SocialFacade.kt
> +   * @param text search criteria.
```suggestion
   * @param name text search criteria.
```

2022-03-24 22:54 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/application/social/SocialFacade.kt
> +   * Get user by name
```suggestion
   * Returns a [Flow] of the [Profile] with the given name
```

2022-03-25 00:24 UTC, Fouad-sys approved these changes

2022-03-25 00:24 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingTabBar.kt
>  }
[Nitpick] Missing documentation of the class parameters

2022-03-25 00:24 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingTabBar.kt
> -fun rememberProfileTabBarState(
[Nitpick] Missing documentation of the function parameters

2022-03-25 00:24 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingTabBar.kt
>  /** Implementation of the ProfileTabBarState */
```suggestion
/** Implementation of the SettingTabBarState */
```

2022-03-25 00:32 UTC, Fouad-sys approved these changes

2022-03-25 00:32 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingTabBar.kt
>  /** Function used to remember the state of the ProfileTabBar */
```suggestion
/** Function used to remember the state of the SettingTabBar */
```

2022-03-25 00:32 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingTabBar.kt
> +private class SettingTabBarStateImpl(
[Nitpick] Missing documentation of the class parameters

2022-03-25 00:32 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
> + * Composes the settings header given the profile [state]. Displays also the ProfilePicture,
```suggestion
 * Composes the settings header given the profile [SettingScreenState]. Displays also the ProfilePicture,

```

2022-03-25 00:32 UTC, Fouad-sys commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
> + * SettingsButton, name and email of th user profile
```suggestion
 * SettingsButton, name and email of the user's profile

```

2022-03-25 00:32 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/social/SocialScreenState.kt
> +  val onPersonClick: (P) -> Unit
Should probably be `fun onPersonClick(person: P)` to be consistent with how callbacks are defined in other states.

2022-03-25 00:32 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/social/SocialScreen.kt
>   * @param modifier modifier the [Modifier] for the composable.
Missing some documentation.

2022-03-25 00:32 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/social/SocialScreen.kt
> +    onPersonClick: (P) -> Unit,
Missing some documentation.

2022-03-25 00:32 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
> +      modifier = modifier)
Slots should use not be capitalized.

2022-03-25 00:32 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/UserScreenSlot.kt
> +fun UserScreenSlot(
`UserScreen` might be a better name here.

2022-03-25 00:32 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulProfileScreen.kt
> +  override val email = ""
We should probably refine the hierarchy of `ProfileScreenState` so it doesn't receive an `email` (and does not need to display it).

2022-03-25 00:32 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulHome.kt
> +const val ProfileRoute = "profile"
This should be `private`.

2022-03-25 00:32 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulFollowingScreen.kt
> +    override var searchFieldInteraction: MutableInteractionSource,
Could these fields be some `val`s ?

2022-03-25 12:25 UTC, KurohanaJuri commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/UserScreen.kt
> + * @param Matches the part that is responsible for the list of all matches
Some parameters are missing

2022-03-25 12:25 UTC, KurohanaJuri commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/social/SocialScreenState.kt
> +  fun onPersonClick(person: P)
Can you add an explanation for the parameter `person`

2022-03-25 12:25 UTC, KurohanaJuri commented on mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/SocialFacadeTest.kt
> +  fun get_successfully() = runTest {
Can you add more information in the name, it's difficult to understand what it's the condition lead to a success

2022-03-25 12:25 UTC, KurohanaJuri commented on mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/SocialFacadeTest.kt
> +  fun get_unsuccessfully() = runTest {
Same that above

2022-03-25 15:09 UTC, alexandrepiveteau reviewed
Looking great ! I think there's something off with the CI as the code doesn't seem to compile, but otherwise it looks good to me.

2022-03-25 15:09 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
> + * SettingsButton, name and email of the user's profile
Something might be a bit off in the formatting here.

2022-03-25 15:09 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/setting/SettingScreen.kt
> +    ) { Icon(Icons.Default.Edit, "Edit profile icon") }
Prefer using a value from `LocalizedStrings` if you provide a content description, rather than a hardcoded string literal.

2022-03-25 15:09 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/profile/UserScreen.kt
> +    ProfileTabBar: @Composable () -> Unit,
`Header` an `ProfileTabBar` should be named `header` and `profileTabBar`.

2022-03-25 15:09 UTC, alexandrepiveteau commented on mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/ui/social/SocialScreenTest.kt
> +  fun list_clickOnUser() {
I'd add the expected result of the test it its name.

2022-03-25 16:58 UTC, alexandrepiveteau submitted a review, later dismissed

2022-03-26 12:52 UTC, KurohanaJuri approved these changes

2022-03-26 13:12 UTC, alexandrepiveteau approved these changes

2022-03-26 13:14 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/application/social/SocialFacade.kt
> +  }
Also, are you sure `catch { null }` does anything ? I think you meant

```kotlin
.catch { emit(null) }
```

2022-03-26 13:35 UTC, merged