Add my email to README
epfl-SDP/android pull request #18
Opened 2022-02-28 18:53 UTC by barmettlerl

2022-02-28 21:50 UTC, Fouad-sys submitted a review, later dismissed

2022-02-28 22:33 UTC, alexandrepiveteau submitted a review, later dismissed

2022-03-01 08:53 UTC, matt989253 submitted a review, later dismissed

2022-03-01 10:08 UTC, BadrTad commented
Hey @barmettlerl, can you make sure please in future PRs that your commit history is as clean as possible. So that reviewers can be more efficient. Thank you !

2022-03-02 12:43 UTC, alexandrepiveteau requested changes

2022-03-02 12:43 UTC, alexandrepiveteau commented on README.md
> +| Lars Barmettler      | lars.barmettler@epfl.ch |
```suggestion
| Lars Barmettler      | lars.barmettler@epfl.ch |
| Matthieu Burguburu   | matthieu.burguburu@epfl.ch |
```

2022-03-03 12:33 UTC, matt989253 approved these changes

2022-03-03 13:01 UTC, merged