Contest History Screen
epfl-SDP/android pull request #312
Opened 2022-05-07 18:05 UTC by Fouad-sys

This pull request adds navigation to the list of past and current Tournaments Screen with a button to create a new Tournament.

2022-05-09 17:12 UTC, alexandrepiveteau requested changes

2022-05-09 22:04 UTC, alexandrepiveteau requested changes

2022-05-09 22:04 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/ContestScreen.kt
> +      modifier = modifier.padding(contentPadding),
You're applying the padding twice : once in the `Scaffold`, and once in the `LazyColumn`.

2022-05-09 22:04 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/ContestScreen.kt
> +  FloatingActionButton(
Please use `ExtendedFloatingActionButton` instead.

2022-05-09 22:04 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulContestsScreen.kt
> +) : Contest {}
I don't think the `{}` are necessary.

2022-05-09 22:04 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulContestsScreen.kt
> +  // private set
```suggestion
```

2022-05-09 22:04 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/Contest.kt
> +interface Contest {
I would name this `ContestInfo`, to better distinguish from composables which might be named `Contest`.

2022-05-09 22:04 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/ContestItem.kt
> +        }
You can put the Badge in the lambda directly. A `Row` with a single child will simply wrap it.

2022-05-09 22:04 UTC, alexandrepiveteau commented on mobile/src/main/java/ch/epfl/sdp/mobile/ui/tournaments/ContestItem.kt
> +      text = { Text(contest.name, color = PawniesColors.Green500) },
You should set the font for this text.

2022-05-10 08:25 UTC, KurohanaJuri commented on mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulContestsScreen.kt
> +data class ContestAdapter(
Missing parameters in the documentation

2022-05-10 08:25 UTC, KurohanaJuri commented on mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulContestsScreen.kt
> +          createContest("3", "Never gonna chess", 3.hours, ONGOING, BadgeType.Join))
When you create a dummy data like this, add To-do keyword to notify to other teammate that it is a temporary value

2022-05-10 08:25 UTC, KurohanaJuri commented on mobile/src/main/java/ch/epfl/sdp/mobile/state/StatefulContestsScreen.kt
> +private fun createContest(
Missing documentation

2022-05-10 12:10 UTC, alexandrepiveteau commented
Included in #327.

2022-05-10 12:10 UTC, closed without merging