Chess Sound Addition
epfl-SDP/android pull request #446
Opened 2022-06-01 22:49 UTC by Fouad-sys

2022-06-06 09:36 UTC, alexandrepiveteau requested changes
Looking good, but some tests are not in the right place or test two things at once.

2022-06-06 09:36 UTC, alexandrepiveteau commented on mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/application/SpeechFacadeTest.kt
> +  }
This should not be in `SpeechFacadeTest`. It looks like you're testing both the `AndroidSoundPlayer` and the `SpeechFacade` simultaneously.

2022-06-08 20:06 UTC, alexandrepiveteau commented on mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/Dsl.kt
> +    synthesizer: TextToSpeechFactory = FakeTextToSpeechFactory,
Missing doc

2022-06-08 20:07 UTC, alexandrepiveteau commented on mobile/src/androidTest/java/ch/epfl/sdp/mobile/test/state/Dsl.kt
> +    synthesizer: TextToSpeechFactory = FakeTextToSpeechFactory,
Also, you should provide the `SoundPlayer` as an argument.

2022-06-08 20:15 UTC, alexandrepiveteau submitted a review, later dismissed
LGTM

2022-06-09 10:19 UTC, matt989253 approved these changes
Nice feature! And love the sound
(But there seems to be a failing test)

2022-06-09 16:57 UTC, alexandrepiveteau approved these changes

2022-06-09 17:32 UTC, merged