Wiki Update : Add information about Gradle and ktfmt
epfl-SDP/android pull request #50
Opened 2022-03-07 10:55 UTC by KurohanaJuri

2022-03-07 12:32 UTC, alexandrepiveteau approved these changes
Thanks !

2022-03-07 12:32 UTC, alexandrepiveteau commented on wiki/Home.md
> +![ExepectedGradle](image/ExpectedGradle.png)
```suggestion
![ExpectedGradle](image/ExpectedGradle.png)
```

2022-03-07 12:32 UTC, alexandrepiveteau commented on wiki/Home.md
> +If you tab isn't like the one on the screen shot, go to `File->Settings...->Experimental`,
```suggestion
If your tab isn't like the one on the screen shot, go to `File->Settings...->Experimental`,
```

2022-03-07 14:05 UTC, alexandrepiveteau approved these changes

2022-03-07 14:28 UTC, BadrTad commented on wiki/Home.md
> +If your tab isn't like the one on the screen shot, go to `File->Settings...->Experimental`,
```suggestion
If your tab isn't like the one on the screenshot, go to `File->Settings...->Experimental`,
```

2022-03-07 14:43 UTC, BadrTad requested changes

2022-03-07 14:43 UTC, BadrTad commented on wiki/Home.md
> +inside `Gradle` section, uncheck `Do not build Gradle task list during Gradle sync`
Proposition: This step alone didn't help to show Gradle tasks tab even after I reloading the IDE. I had to re-build the project. Maybe it's worth to mentioning.

2022-03-07 17:27 UTC, alexandrepiveteau approved these changes

2022-03-07 17:29 UTC, matt989253 submitted a review, later dismissed

2022-03-08 09:52 UTC, alexandrepiveteau approved these changes

2022-03-08 10:03 UTC, BadrTad approved these changes

2022-03-08 10:56 UTC, merged